spring:
  active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # Flyway cuidará do schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true

flyway:
  enabled: true
  locations: classpath:db/migration

api:
  security:
    token:
      secret: ${API_SECRET:default-secret} # valor default opcional
  cors:
    allowed-origins: ${GRID_UI}

ccee:
  base-url: "https://www.ccee.org.br/web/guest/precos/painel-precos"